# title: My GitHub Blog
# description: "Welcome to my GitHub Pages blog!"
# remote_theme: aterenin/minima-reboot
# markdown: kramdown  # GitHub Pagesì˜ ê¸°ë³¸ Markdown ì—”ì§„
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
title: My GitHub Blog
description: "Welcome to my GitHub Pages blog!"
remote_theme: aterenin/minima-reboot
markdown: kramdown  # GitHub Pagesì˜ ê¸°ë³¸ Markdown ì—”ì§„
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
mathjax: true  # ğŸ”¥ ì¶”ê°€!
