title: My GitHub Blog
description: "Welcome to my GitHub Pages blog!"
remote_theme: aterenin/minima-reboot
markdown: kramdown  # GitHub Pages의 기본 Markdown 엔진
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge